SCROLL_ZONE_WIDTH_RATIO = 0.94
SCROLL_ZONE_WIDTH_PIXELS = 80

JITTER_THRESHOLD = 15
SLOW_SCROLL_MAX_SPEED = 150
MIN_DISTANCE_BETWEEN_CAPTURES = 60
MIN_DISTANCE_SLOW_SCROLL = 100
SLOW_SCROLL_CADENCE_TIME = 2.5

VELOCITY_CHECK_INTERVAL = 0.5

WHEEL_IDLE_TIME = 1.0
WHEEL_SMART_PAUSE_DEBOUNCE = 0.8
