<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Qapptia.Editor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="DynamicData" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qapptia.Core\Qapptia.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Fonts\**\*.ttf" />
  </ItemGroup>
</Project>
