<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Qapptia.Editor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Fonts\**\*.ttf" />
  </ItemGroup>
</Project>
